In [11]:
import pandas as pd
import numpy as np
from sklearn.metrics import cohen_kappa_score

In [12]:
df = pd.read_csv("annotations_combined.csv").drop(["img_id", "group_id"] , axis=1)
df = df.drop(351 , axis=0).reset_index(drop=True)     # drop a NaN row

# only 4 annotators included
all_4_pen = df[["pen_1", "pen_2", "pen_3", "pen_4"]]                
all_4_hair = df[["hair_1", "hair_2", "hair_3", "hair_4"]]


# The following code only considers the data with the fifth annotator included
df_5 = df[df["hair_5"].notna()].dropna()     # there is a missing value
five_pen = df_5[["pen_1", "pen_2", "pen_3", "pen_4", "pen_5"]]
five_hair = df_5[["hair_1", "hair_2", "hair_3", "hair_4", "hair_5"]]

In [13]:
# Cohen Cappa scores without the fifth annotator

# pen
average_pen = 0
pen_pairs = 0
cohen_scores_pen = np.zeros((4,4))
for i in range(1,5):
    for j in range(i+1,5):
        cohen_scores_pen[i-1,j-1] = cohen_kappa_score(all_4_pen[f"pen_{i}"], all_4_pen[f"pen_{j}"])
#        cohen_scores_pen[j-1,i-1] = cohen_scores_pen[i-1,j-1]           # just for symmetry
        average_pen += cohen_scores_pen[i-1,j-1]
        pen_pairs += 1

print(f"Cohen Kappa scores for pen: \n {cohen_scores_pen.round(3)} \n")

# hair
average_hair = 0
hair_pairs = 0
cohen_scores_hair = np.zeros((4,4))
for i in range(1,5):
    for j in range(i+1,5):
        cohen_scores_hair[i-1,j-1] = cohen_kappa_score(all_4_hair[f"hair_{i}"], all_4_hair[f"hair_{j}"], weights="linear")
#        cohen_scores_hair[j-1,i-1] = cohen_scores_hair[i-1,j-1]        # just for symmetry
        average_hair += cohen_scores_hair[i-1,j-1]
        hair_pairs += 1

print(f"Cohen Kappa scores for hair: \n {cohen_scores_hair.round(3)} \n")


print(f"Average score for pen: {round(average_pen/pen_pairs, 3)}")
print(f"Average score for hair: {round(average_hair/hair_pairs, 3)}")

Cohen Kappa scores for pen: 
 [[0.    0.9   0.908 0.756]
 [0.    0.    0.875 0.733]
 [0.    0.    0.    0.749]
 [0.    0.    0.    0.   ]] 

Cohen Kappa scores for hair: 
 [[0.    0.765 0.741 0.714]
 [0.    0.    0.731 0.71 ]
 [0.    0.    0.    0.789]
 [0.    0.    0.    0.   ]] 

Average score for pen: 0.82
Average score for hair: 0.742


In [14]:
# Cohen Cappa scores for images with 5 annotators

# for pen
average_pen = 0
pen_pairs_5 = 0
cohen_scores_pen = np.zeros((5,5))
for i in range(1,6):
    for j in range(i+1,6):
        cohen_scores_pen[i-1,j-1] = cohen_kappa_score(five_pen[f"pen_{i}"], five_pen[f"pen_{j}"])
#        cohen_scores_pen[j-1,i-1] = cohen_scores_pen[i-1,j-1]           # just for symmetry
        average_pen += cohen_scores_pen[i-1,j-1]
        pen_pairs_5 += 1
        
print(f"Cohen Kappa scores for pen: \n {cohen_scores_pen.round(3)} \n")

# for hair
average_hair = 0
hair_pairs_5 = 0
cohen_scores_hair = np.zeros((5,5))
for i in range(1,6):
    for j in range(i+1,6):
        cohen_scores_hair[i-1,j-1] = cohen_kappa_score(five_hair[f"hair_{i}"], five_hair[f"hair_{j}"], weights="linear")
#        cohen_scores_hair[j-1,i-1] = cohen_scores_hair[i-1,j-1]        # just for symmetry
        average_hair += cohen_scores_hair[i-1,j-1]
        hair_pairs_5 += 1


print(f"Cohen Kappa scores for hair: \n {cohen_scores_hair.round(3)} \n")


print(f"Average score for pen: {round(average_pen/pen_pairs_5, 3)}")
print(f"Average score for hair: {round(average_hair/hair_pairs_5, 3)}")

Cohen Kappa scores for pen: 
 [[0.    0.9   0.911 0.844 0.913]
 [0.    0.    0.877 0.821 0.904]
 [0.    0.    0.    0.835 0.89 ]
 [0.    0.    0.    0.    0.834]
 [0.    0.    0.    0.    0.   ]] 

Cohen Kappa scores for hair: 
 [[0.    0.776 0.732 0.717 0.72 ]
 [0.    0.    0.734 0.71  0.733]
 [0.    0.    0.    0.8   0.731]
 [0.    0.    0.    0.    0.727]
 [0.    0.    0.    0.    0.   ]] 

Average score for pen: 0.873
Average score for hair: 0.738
